jump-dev/MultiObjectiveAlgorithms.jl

README.md, src/MOO.jl, src/algorithms/EpsilonConstraint.jl, test/algorithms/EpsilonConstraint.jl
Rather than sampling, setting `ObjectiveAbsoluteTolerance` lets you explicitly set the epsilon used.
x-ref: https://github.com/odow/MOO.jl/issues/10#issuecomment-1419958762
=> Add ObjectiveAbsoluteTolerance and use in EpsilonConstraint

src/MultiObjectiveAlgorithms.jl, src/algorithms/EpsilonConstraint.jl, src/algorithms/Lexicographic.jl, test/runtests.jl, test/test_utilities.jl
=> Add tests for filter_nondominated

README.md, src/algorithms/KirlikSayin.jl, test/algorithms/KirlikSayin.jl
I added a few line for the MOI.MAX_SENSE. Added tests for assignment and 4-objective knapsack.
=> Add KirlikSayin algorithm

README.md, src/algorithms/Dichotomy.jl, test/algorithms/Dichotomy.jl
=> Rename NISE as Dichotomy

README.md, src/algorithms/Chalmet.jl, test/algorithms/Chalmet.jl
Link for the algorithm: https://doi.org/10.1016/0377-2217(86)90093-7
I looked at NISE.jl implementation. Maybe a few more functions can be added to make `optimize_multiobjective!` more readable although I was not sure how to set it up.
Also, I did not add any attributes to this one either.
Closes #15
=> Add Chalmet algorithm

Project.toml, src/MultiObjectiveAlgorithms.jl, test/algorithms/Dichotomy.jl
=> Support VectorQuadraticFunction objectives

src/MultiObjectiveAlgorithms.jl, src/algorithms/Dichotomy.jl, src/algorithms/DominguezRios.jl, src/algorithms/EpsilonConstraint.jl, src/algorithms/KirlikSayin.jl, test/algorithms/EpsilonConstraint.jl, test/test_model.jl
Closes #44
This also fixes a bunch of cases which assume `MOI.OPTIMAL` is the only status that may be returned.
=> Fix MOA with local solvers not supporting delete

src/MultiObjectiveAlgorithms.jl
This gives warning when using the package
```julia
WARNING: method definition for set at /home/blegat/.julia/packages/MultiObjectiveAlgorithms/80Aze/src/MultiObjectiveAlgorithms.jl:348 declares type variable S but does not use it.
WARNING: method definition for set at /home/blegat/.julia/packages/MultiObjectiveAlgorithms/80Aze/src/MultiObjectiveAlgorithms.jl:372 declares type variable S but does not use it.
```
so it's worth doing a patch release with this fix
=> Remove unused S parameter

src/algorithms/EpsilonConstraint.jl, test/algorithms/EpsilonConstraint.jl
=> Fix finite termination of EpsilonConstraint

src/MultiObjectiveAlgorithms.jl, test/test_model.jl
Currently, `solve_time` call is passed to the solver and the returned time corresponds to the last optimization only.
=> Support solve_time(model)

src/MultiObjectiveAlgorithms.jl, src/algorithms/DominguezRios.jl, src/algorithms/KirlikSayin.jl
Closes #60 
From a quick survey of some papers, it seems that computing the nadir point is non-trivial in the general case of N>2 objectives, so let's just give the user a more detailed warning of what went wrong and what they should do about it.
=> Fix warning on non-finite nadir point

README.md, src/algorithms/TambyVanderpooten.jl, test/algorithms/TambyVanderpooten.jl
Link: https://doi.org/10.1287/ijoc.2020.0953
This algorithm keeps a list of upper bounds and the set of 'defining points' associated with each upper bound. After selecting an upper bound to find the next non-dominated point, one of the defining points for that upper bound is used as a starting solution. A warning is raised if the solver does not support `VariablePrimalStart`.
=> Add Tamby Vanderpooten algorithm

Project.toml, src/MultiObjectiveAlgorithms.jl, src/algorithms/EpsilonConstraint.jl, test/algorithms/EpsilonConstraint.jl, test/runtests.jl
<s>Currently blocked by the lack of `Utilities.eval_variables(f::Function, ::ScalarNonlinearFunction)`.</s>
=> Add support for VectorNonlinearFunction objectives

src/MultiObjectiveAlgorithms.jl, src/algorithms/Lexicographic.jl
Hi, I have added support for TimeLimitSec to the Lexicographic search algorithm.
- Given a fixed sequence of objectives, it returns the last solution found, even if not proved optimal for all objectives. The last found is very likely the best one found for this fixed sequence of objectives thanks to the additional constraints that are added after each iteration. (By the way, could we not warm-start each iteration with the solution previously found?)
- When solutions for all permutations of the objectives are asked, it simply collects all the solutions found by the above procedure for as many permutations as possible, whether optimal or not, and filters the dominated ones as before.
I hope that makes sense, I just started learning JuMP so it might not be perfect.
=> Add support for TimeLimitSec to Lexicographic

src/algorithms/DominguezRios.jl, src/algorithms/KirlikSayin.jl, src/algorithms/TambyVanderpooten.jl, test/algorithms/DominguezRios.jl, test/algorithms/KirlikSayin.jl
I think #72 is because, in DominguezRios, we have `ϵ = 1 / (2 * n * (maximum(yN - yI) - 1))`. Because of the objective range, this does not work with models we solve during iterations.
Also, in `KirlikSayin` and `TambyVanderpooten`, we only find one nondominated point. This has to do with management of search space (again because of the nadir point)
We already overestimate the nadir point by reversing `ObjectiveSense`. Maybe, adding +1 to `yN` can solve the problem.
I am working on a PR. This fixes the issue but messes up the order of nondominated points which causes other tests to fail so I will sort the set of nondominated points in `Y_N` before comparing.
=> Over-estimate nadir point in algorithms to fix cycling

test/algorithms/Lexicographic.jl, test/test_model.jl
HiGHS v1.7.1 can now return a feasible point, even if the problem is unbounded.
=> Fix test return for new HiGHS version

src/MultiObjectiveAlgorithms.jl, test/test_model.jl
If we forward to the solver, it will just be whatever the last solve was, which is probably not meaningful.
Closes #86
=> Disallow querying is_set_by_optimize attributes unless explicitly supported

README.md, src/MultiObjectiveAlgorithms.jl, test/test_model.jl
=> Add ComputeIdealPoint attribute

src/MultiObjectiveAlgorithms.jl, src/algorithms/Dichotomy.jl, test/algorithms/Dichotomy.jl
Hi, 
This PR adds time limits to solving for ideal points, and the first solves of the dichotomy algorithm.
I realise that timing-out when solving for ideal points indicates that the time limit is probably way to small to get anything meaningful from the multi-objective formulation, but this was an edge case I faced, leading to some behaviour I was not expecting.
Also, this brings this package more in line with other MO solvers.  For instance if I just used Gurobi to solve the multi-objective function, then for sure I would expect it to satisfy my time limit.  But currently with this package the solver could go far beyond my time limit. For example, the start time **before** computation of ideal points is not passed down to any of the algorithms, so if it takes a long time to solve for …
=> Add time limits to compute ideal point & dichotomy starting solutions

src/MultiObjectiveAlgorithms.jl
We should probably time out generating primal solutions, not computing the objective bound.
=> Move computing the ideal point after the optimizer has run

src/MultiObjectiveAlgorithms.jl, src/algorithms/Dichotomy.jl, src/algorithms/DominguezRios.jl, src/algorithms/EpsilonConstraint.jl, src/algorithms/KirlikSayin.jl, src/algorithms/TambyVanderpooten.jl, test/algorithms/Chalmet.jl, test/algorithms/DominguezRios.jl, test/algorithms/EpsilonConstraint.jl, test/algorithms/KirlikSayin.jl, test/algorithms/TambyVanderpooten.jl
A few of the algorithms compute the ideal point as part of the solve. No need to repeat work.
In addition, the epsilon constraint was computing the edge solutions twice, because I am not clever.
=> Enable algorithms to update the ideal_point during a solve

src/algorithms/TambyVanderpooten.jl, test/algorithms/TambyVanderpooten.jl
=> Various fixes to TambyVanderpooten

src/MultiObjectiveAlgorithms.jl, test/test_utilities.jl
It's the cause of #115 failing
=> Fix comparison for non-dominated to account for tolerances

src/algorithms/Chalmet.jl, src/algorithms/KirlikSayin.jl, src/algorithms/TambyVanderpooten.jl, test/problems.jl
=> Fix various usages of MOI.delete

src/MultiObjectiveAlgorithms.jl, src/algorithms/Lexicographic.jl, test/algorithms/Lexicographic.jl
=> Add a warning when lexicographic used with default args and 5+ objectives

src/algorithms/Dichotomy.jl, test/algorithms/Dichotomy.jl
=> Allow Dichotomy to return solutions on error

ext/MultiObjectiveAlgorithmsPolyhedraExt.jl, src/MultiObjectiveAlgorithms.jl, src/algorithms/Chalmet.jl, src/algorithms/Dichotomy.jl, src/algorithms/DominguezRios.jl, src/algorithms/EpsilonConstraint.jl, src/algorithms/KirlikSayin.jl, src/algorithms/Lexicographic.jl, src/algorithms/RandomWeighting.jl, src/algorithms/TambyVanderpooten.jl, test/test_model.jl
=> Add support for interrupting during the solve loops

.github/workflows/ci.yml, README.md, src/MultiObjectiveAlgorithms.jl, test/algorithms/Chalmet.jl, test/algorithms/Dichotomy.jl, test/algorithms/EpsilonConstraint.jl, test/algorithms/Lexicographic.jl, test/algorithms/RandomWeighting.jl, test/problems.jl, test/test_utilities.jl
=> Sort based on optimization sense
